version: '3.8'
services:
  web:
    build: .
    container_name: todo-app

    ports:
      - "8000:8000"
    environment:

      DATABASE_URL: "sqlite:///./data/sql_app.db"
    volumes:
      - ./data:/app/data 
    restart: always

    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]